# Generated by Django 6.0.7 on 2026-07-28 19:06

import django.db.models.deletion
import webapi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0002_alter_product_product_type_remove_product_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=webapi.models.product_image_path)),
                ('image_order', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='webapi.product')),
            ],
            options={
                'ordering': ['image_order'],
            },
        ),
    ]
