export const environment = {
  production: true,
  apiUrl: '/api',
  whatsappNumber: '+5493516801386',
  whatsappLink: 'https://wa.me/5493516801386',
  product_types: [
    'remeras',
    'camperas',
    'chalecos',
    'pantalones',
    'calzado',
    'cascos',
    'lentes',
    'gorras',
    'guantes',
    'mascaras',
    'proteccion_auditiva',
    'proteccion_respiratoria',
    'emergencias',
    'senalizacion',
    'limpieza_e_higiene',
    'herramientas',
    'ferreteria',
    'sogas_e_hilos'
  ],
};
